#!/bin/zsh

PRINTER="MFC7360N"

function long {
        lp -d $PRINTER $1 -n $2 -P $3 \
                -o fit-to-page \
                -o page-top=36 \
                -o page-bottom=36 \
                -o page-left=36 \
                -o page-right=36 \
}

function odd {
        lp -d $PRINTER $1 -P $(seq 1 2 $2 |\
                sed ':a;N;$!ba;s/\n/,/g') \
                -o fit-to-page
}

function even {
        lp -d $PRINTER $1 -P $(seq 2 2 $2 |\
                sed ':a;N;$!ba;s/\n/,/g') \
                -o fit-to-page
}

function default {
        lp -d $PRINTER $1 -n $2 \
                -o fit-to-page
}

function quick {
        default $1 1
}

case "$1" in 
        -l)
                long $2 $3 $4
                ;;
        -o)
                odd $2 $3
                ;;
        -e)
                even $2 $3
                ;;
        -q)
                quick $2
                ;;
        -d)
                default
                ;;
        esac

exit 0
